import csv

translations = {
    r"]  not found": r"] が見つかりません",
    r"] : specClass is null": r"] : specClass が null です",
    r"] already loaded (perhaps from jar file, or due to a reference from another class), skipping compilation.": r"] はすでにロードされています（jarファイルまたは別クラスからの参照など）。コンパイルをスキップします。",
    r"] characters across multiple files exceeded.": r"] 文字を複数ファイルにまたがって超過しました。",
    r"] for ": r"]：",
    r"] for context menu": r"] コンテキストメニュー用",
    r"] for ship system [": r"] 艦船システム用 [",
    r"] has = ('assignment') operator in its conditions, this is most likely an error": r"] の条件式に =（代入）演算子が含まれています。これはおそらくエラーです",
    r"] has == ('equals') operator in its script, this is most likely an error": r"] のスクリプトに ==（等価）演算子が含まれています。これはおそらくエラーです",
    r"] has invalid value [": r"] は無効な値です [",
    r"] has less than 4 elements": r"] の要素が4つ未満です",
    r"] in [": r"] （ [",
    r"] is invalid": r"] は無効です",
    r"] is not a valid market condition (condition requirements data for: [": r"] は無効な市場状況です（条件要件データ: [",
    r"] is not a valid market condition, was loading: condition_gen_data.csv": r"] は無効な市場状況です。ロード中: condition_gen_data.csv",
    r"] is required": r"] が必要です",
    r"] not found": r"] が見つかりません",
    r"] not found in ": r"] が以下に見つかりません ",
    r"] not found in packages:\n": r"] がパッケージに見つかりません:\n",
    r"] not found on hull [": r"] が船体に見つかりません [",
    r"] not found or failed to load": r"] が見つからないか、ロードに失敗しました",
    r"] not found while instantiating submarket with id [": r"] が見つかりません。サブマーケット(id: [) のインスタンス化中",
    r"] not found while loading drop_groups.csv": r"] が見つかりません。drop_groups.csv のロード中",
    r"] not found while loading salvage_entity_gen_data.csv": r"] が見つかりません。salvage_entity_gen_data.csv のロード中",
    r"] not found!!!": r"] が見つかりません!!!",
    r"] only used once; rule id: [": r"] は一度しか使われていません; ルールID: [",
    r"] to JSON": r"] を JSON に",
    r"] to [": r"] を [",
    r"] while loading [": r"] （ロード中: [",
    r"], ": r"], ",
    r"], assuming it's a core skin not used in total conversion.": r"], 大型PLUGINでは使われないコラスキンとみなします。",
    r"], assuming it's a core variant not used in total conversion.": r"], 大型PLUGINでは使われないコアバリアントとみなします。",
    r"], it's not listed in skill_data.csv.": r"], skill_data.csv に記載がありません。",
    r"], last added row:\n": r"], 最後に追加された行:\n",
    r"], must be String or DeployedFleetMember": r"], String または DeployedFleetMember である必要があります",
    r"], this is likely a typo": r"], これはタイプミスの可能性が高いです",
    r"], was already loaded": r"], 既にロード済みです",
    r"], was loading: condition_gen_data.csv)": r"], ロード中でした: condition_gen_data.csv)",
    r"].\n": r"].\n",
    r"a brief shutdown of a ship's reactor containment field and resulting in": r"艦の原子炉格納フィールドの短時間のシャットダウンにより、",
    r"a flicker in a ship's fore radiation screens and resulting in": r"艦の前方放射線スクリーンのちらつきにより、",
    r"a loss of a ": r"〜の喪失",
    r"a loss of cargo": r"貨物の喪失",
    r"a loss of crew": r"乗組員の喪失",
    r"a loss of fuel": r"燃料の喪失",
    r"a loss of marines": r"海兵隊員の喪失",
    r"a loss of supplies": r"物資の喪失",
    r"a loss of the ": r"〜の喪失",
    r"a shutdown of a ship's reactor containment field and resulting in": r"艦の原子炉格納フィールドのシャットダウンにより、",
    r"a spot failure of a ship's artificial gravity generator and resulting ina life support system malfunction and resulting in": r"艦の人工重力発生装置の局所的な故障と、それに伴う生命維持システムの異常により、",
    r"a temporary failure of a ship's artificial gravity generator and resulting ina major life support system malfunction and resulting in": r"艦の人工重力発生装置の一時的な故障と、それに伴う重大な生命維持システムの異常により、",
    r"after reaching the maximum level.": r"最大レベル到達後。",
    r"all colonies": r"全てのコロニー",
    r"all combat ships": r"全ての戦闘艦",
    r"all drones recalled": r"全ドローン帰還",
    r"all fighters": r"全ての戦闘機",
    r"all ships": r"全ての艦船",
    r"all ships with fighter bays": r"飛行甲板を持つ全ての艦船",
    r"and a colony established here would likely be eradicated in short order.": r"そしてここに設立されたコロニーは、おそらく短期間で壊滅するでしょう。",
    r"approximately ": r"約 ",
    r"armor rating": r"装甲値",
    r"assault ": r"強襲 ",
    r"assign to task ": r"任務に割り当てる ",
    r"assigning ": r"割り当て中 ",
    r"asslt gun": r"強襲砲",
    r"at this location": r"この場所で",
    r"available_ ": r"利用可能な_ ",
    r"avoid ": r"回避 ",
    r"avoiding ": r"回避中 ",
    r"avoiding abyssal hyperspace": r"深淵の超空間を回避中",
    r"avoiding contact": r"接触を回避中",
    r"bar event id": r"酒場イベントID",
    r"base price": r"基本価格",
    r"base value": r"基本価値",
    r"based on the s-plugins you've built into this hull. Please confirm your orders.": r"この船体に組み込まれたS-PLUGINに基づいています。命令を確認してください。",
    r"be invalid. Please ensure that it matches the": r"無効です。一致していることを確認してください：",
    r"beam speed": r"ビーム速度",
    r"because legacyapp is not pirateable. ": r"スターファーラーは海賊行為の対象にはならないため。",
    r"below tenth": r"10分の1未満",
    r"bonus effects": r"ボーナス効果",
    r"bonus experience": r"ボーナス経験値",
    r"bonus_ ": r"ボーナス_ ",
    r"build time": r"建造時間",
    r"built in weapon": r"内蔵兵器",
    r"built into": r"組み込み",
    r"burst delay": r"バースト遅延",
    r"burst size": r"バーストサイズ",
    r"but as a commission holder, you would be allowed to establish a colony here.": r"しかし、あなたは任命状を持っているため、ここにコロニーを設立することが許可されるでしょう。",
    r"but it's probably a bad idea. Random crashes, incompatibility with other plugins, etc may result.": r"しかし、おそらく悪い考えです。ランダムなクラッシュや他のPLUGINとの非互換性などが発生する可能性があります。",
    r"but when they discover this special shout out they will ": r"しかし、彼らがこの特別なメッセージを見つけた時、彼らは ",
    r"buy:": r"購入:",
    r"campaign battle result": r"キャンペーン戦闘結果",
    r"campaign state in session": r"キャンペーン状態がセッション中にあります",
    r"canceling tasks on ": r"〜のタスクをキャンセル中 ",
    r"capable officers in command of combat-ready ships": r"戦闘準備の整った艦を指揮する有能な士官",
    r"capture ": r"占領 ",
    r"cargo space": r"貨物容量",
    r"charge up": r"チャージアップ",
    r"click here to paste code": r"クリックしてコードを貼り付ける",
    r"click here to paste code from clipboard": r"クリックしてクリップボードからコードを貼り付ける",
    r"cloak activation": r"クローク起動",
    r"cloak disabled": r"クローク無効",
    r"cloak flux/sec": r"クローク フラックス/秒",
    r"code in your confirmation email and try again.": r"確認メールのコードを入力して、もう一度やり直してください。",
    r"codex variant id": r"コーデックスバリアントID",
    r"colony controlled by ": r"〜に支配されたコロニー ",
    r"color:": r"色:",
    r"combat officer": r"戦闘士官",
    r"command frequency open": r"司令部周波数オープン",
    r"command point": r"司令ポイント",
    r"command points: +1": r"司令ポイント: +1",
    r"command points: +2": r"司令ポイント: +2",
    r"compiling quad": r"クアッドのコンパイル中",
    r"consuming ~": r"約〜を消費",
    r"control ": r"支配 ",
    r"cost mult": r"コスト倍率",
    r"course laid in for": r"〜へ進路を設定",
    r"cr %/day": r"CR %/日",
    r"cr: ": r"CR: ",
    r"crew available": r"利用可能な乗組員",
    r"crew understrength": r"乗組員不足",
    r"currently installed": r"現在インストールされている",
    r"currently mounted": r"現在装備されている",
    r"damage to a ": r"〜へのダメージ",
    r"damage to the ": r"〜へのダメージ",
    r"damage type|Kinetic": r"キネティック(運動)",
    r"damaged fighter wing": r"損傷した戦闘機中隊",
    r"damaged ship": r"損傷した艦船",
    r"defaultName not set": r"defaultName が設定されていません",
    r"defend ": r"防衛 ",
    r"defend on ": r"〜で防衛 ",
    r"defending ": r"防衛中 ",
    r"defense id": r"防衛ID",
    r"defined-in": r"定義元",
    r"demand class": r"需要クラス",
    r"deploying drones": r"ドローン展開中",
    r"deployment points": r"配備ポイント",
    r"destroyer escort on ": r"〜の駆逐艦による護衛 ",
    r"developed a slow leak in the off hours": r"時間外にゆっくりとした漏れが発生した",
    r"dialogType should not be null here": r"ここでは dialogType を null にすることはできません",
    r"did once": r"一度だけ行った",
    r"disengaging from ": r"〜から離脱中 ",
    r"dmg: ": r"ダメージ: ",
    r"dmg: ---": r"ダメージ: ---",
    r"eliminate ": r"排除 ",
    r"engage ": r"交戦 ",
    r"engaged in battle": r"戦闘中",
    r"engine boost": r"エンジンブースト",
    r"eradicated in short order": r"短期間で壊滅",
    r"excess stockpiles of ~": r"約〜の過剰な備蓄",
    r"export value": r"輸出額",
    r"exported ~": r"約〜を輸出",
    r"f/s (base cap)": r"f/s (基本容量)",
    r"f/s (base rate)": r"f/s (基本レート)",
    r"f/u (base cap)": r"f/u (基本容量)",
    r"f/u (base rate)": r"f/u (基本レート)",
    r"failed after exposure to an unexpected burst of radiation": r"予期せぬ放射線バーストを浴びた後に故障した",
    r"field refit": r"野戦改修",
    r"fighter LPC": r"戦闘機LPC",
    r"fighter LPCs": r"戦闘機LPC",
    r"fighter bays": r"飛行甲板",
    r"fighter blueprints": r"戦闘機のブループリント",
    r"fighter wing": r"戦闘機中隊",
    r"fighters from piloted ship": r"搭乗艦からの戦闘機",
    r"finishing repairs": r"修理完了",
    r"fleet points: +10": r"艦隊ポイント: +10",
    r"fleet points: +30": r"艦隊ポイント: +30",
    r"fleet pts": r"艦隊ポイント",
    r"flight decks": r"飛行甲板",
    r"flight decks: ": r"飛行甲板: ",
    r"flight time": r"飛行時間",
    r"flux capacitor": r"フラックスコンデンサー",
    r"flux capacitors": r"フラックスコンデンサー",
    r"flux capacity": r"フラックス容量",
    r"flux dissipation": r"フラックス放散",
    r"flux vent": r"フラックスダクト",
    r"flux vents": r"フラックスダクト",
    r"flux|flux capacity|flux level": r"フラックス|フラックス容量|フラックスレベル",
    r"for ": r"対象: ",
    r"for the use of one ": r"1つの使用につき ",
    r"for the use of the ": r"〜の使用につき ",
    r"free assign": r"自由割り当て",
    r"free assign: ": r"自由割り当て: ",
    r"free roam": r"自由行動",
    r"from path [": r"パス [ から",
    r"from your cargo holds": r"貨物倉から",
    r"fuel: %d": r"燃料: %d",
    r"full escort on ": r"〜の完全な護衛 ",
    r"fully surveyed": r"完全に調査済み",
    r"gen imported": r"生成インポート",
    r"giving orders": r"命令を出す",
    r"god damned good at writing top secret code ": r"最高機密コードを書くのがクソ上手い ",
    r"governed colony": r"統治下のコロニー",
    r"grants bonus experience, depending on hull size.": r"船体の大きさに応じてボーナス経験値を与えます。",
    r"harass ": r"嫌がらせ ",
    r"hard flux": r"ハードフラックス",
    r"heavy cruiser": r"重巡洋艦",
    r"heavy escort ": r"重護衛 ",
    r"higher resolution.": r"より高い解像度。",
    r"hits %": r"命中率 %",
    r"hullSpec is null for variant [": r"バリアントの hullSpec が null です [",
    r"imported ~": r"約〜を輸入",
    r"in holding pattern": r"待機パターン中",
    r"in hyperspace": r"超空間(ハイパースペース)内",
    r"in the ": r"〜の中で",
    r"in this operation are %s ": r"この作戦において %s は ",
    r"increased effectiveness of ground operations": r"地上作戦の有効性が増加",
    r"intercept ": r"迎撃 ",
    r"invalid variant id that won't be found and therefore won't get used": r"見つからず、使用されない無効なバリアントID",
    r"is %s days. If there's a credit shortfall at the end of a month, ": r"は %s 日です。月末にクレジットが不足している場合、",
    r"is higher given the colony's accessibility-based shipping limits.": r"コロニーのアクセス性に基づく輸送制限を考慮すると、より高くなります。",
    r"is recommended when using UI scaling other than 100%, 200%, or 300%.\nOtherwise, certain fonts and other UI elements ": r"100%、200%、または300%以外のUIスケーリングを使用する場合に推奨されます。\nそうでない場合、特定のフォントやその他のUI要素が ",
}

input_file = './chunk_7.csv'
output_file = './chunk_7_translated.csv'

with open(input_file, 'r', encoding='utf-8') as fin, open(output_file, 'w', encoding='utf-8', newline='') as fout:
    reader = csv.reader(fin)
    writer = csv.writer(fout)
    
    header = next(reader)
    writer.writerow(header)
    
    for row in reader:
        if not row:
            writer.writerow(row)
            continue
        key = row[0]
        # check for exact match
        if key in translations:
            writer.writerow([key, translations[key]])
        else:
            # check if it looks like a variable/path or just an empty string
            writer.writerow([key, key])
