import json

translations = {
  "Volturn possesses a thick atmosphere over a world-sea which has been seeded with re-engineered Terra-type life forms that have largely displaced the relatively primitive native organisms which once formed vast drifting colonial mats. The human population lives in a diverse range of floating habitats and subsists largely on farming and processing complex organic compounds.": "ヴォルターンは厚い大気と、惑星全体を覆う海を持つ。その海には遺伝子改変された地球型の生命体がまかれており、かつて広大なコロニーマットを形成して漂っていた比較的原始的な土着生物をほぼ駆逐している。人類は多様な浮遊居住施設に住み、主に複雑な有機化合物の養殖と加工によって生計を立てている。",
  "A near-terran compatible ecosystem has taken tentative hold on this world despite highly abnormal planetary conditions. That this planet maintains a breathable atmosphere (or near enough) is a testament to the tenacity and adaptability of biological life.": "極めて異常な惑星環境にもかかわらず、地球型に近い生態系がこの星に一時的に根付いている。この惑星が呼吸可能な（あるいはそれに近い）大気を維持していることは、生物の粘り強さと適応力を証明している。",
  "Jangala Station": "ジャンガラ・ステーション",
  "A row of taps adorned the wall under bottles from every one of the Core Worlds - and a few from elsewhere. Merchant-captains mingled with off-duty officers at the bar, served by uniformed staff. In one corner a pack of navy cadets shouted and sang, desperate to enjoy their last shift of freedom.": "コア・ワールドの全星系——そして他のいくつかの場所——から集められたボトルの下に、壁を飾るようにタップ（注ぎ口）が並んでいた。バーでは、制服姿のスタッフが給仕する中、商船の船長たちと非番の士官たちが入り混じっていた。片隅では、海軍の士官候補生の一団が、自由な最後のひとときを必死に楽しむかのように叫び、歌っていた。",
  "A slow-firing, medium range energy cannon that delivers an electromagnetic pulse (EMP) and can quickly disable enemy systems/engines. May arc to pluginules near the point of impact.": "電磁パルス(EMP)を放ち、敵のシステムやエンジンを素早く無力化できる、発射速度の遅い中距離エネルギー砲。着弾点付近のモジュールにアーク（放電）が飛ぶことがある。",
  "Extends the range of non-PD fragment weapons and rapidly fires them.": "PD(近接防衛)以外の破片兵器の射程を延長し、連射する。",
  "A supergiant star in a late phase of its mayfly-short stellar life, this class M star has the largest volume of all known stellar types. It has exhausted its core's supply of hydrogen, transitioning smoothly to the fusion of helium, and is likely to proceed onward through the elements up to iron before creating a supernova. Although extraordinarily massive, the outer envelope of the star is extremely sparse and has a relatively low temperature, providing its characteristic hue. This star is casting off its constituent matter at a rapid rate and will form a spectacular nebula. Betelgeuse and Antares are examples of red supergiants known to classical pre-Domain astronomy.": "カゲロウのように短い恒星の寿命の末期にある超巨星であり、このM型星は既知の全恒星タイプの中で最大の体積を持つ。中心部の水素の供給を使い果たし、ヘリウムの核融合へとスムーズに移行しており、超新星爆発を起こす前に鉄までの元素合成をさらに進めていく可能性が高い。とてつもなく巨大だが、星の外層は極めて希薄で比較的温度が低く、それが特徴的な色合いを生み出している。この星は構成物質を急速に放出しており、やがて壮大な星雲を形成するだろう。ベテルギウスやアンタレスは、人類領域(ドメイン)以前の古典天文学に知られていた赤色超巨星の例である。",
  "Although automated machines of war were forbidden in core Domain space, war drones were quietly employed outside of the officially incorporated volume. Frontier garrisons were often bolstered by drone ships, and they were deployed liberally against rebellious worlds to tip the terrible balance of attrition, setting the industrial might of the Domain versus the lives of 'freedom fighters'.\n\nNumerous vulnerabilities leave the Picket-class drone easy to underestimate, but woe to the captain who commits this error. If the Picket is allowed to follow its programming to close aggressively with its target, it will unleash a shockingly dense volume of light-caliber fire to rip apart unarmored hulls.": "人類領域(ドメイン)のコア宙域では自律型戦争機械は禁じられていたが、公式に編入された宙域の外では密かに無人戦闘機（ウォードローン）が使用されていた。辺境の駐屯地はしばしばドローン艦によって補強され、反抗的な世界に対しては、ドメインの工業力と「自由の戦士」たちの命とを天秤にかけるという、恐るべき消耗戦のバランスを傾けるために惜しみなく投入された。\n\n多数の脆弱性を抱えるピケット級ドローンは過小評価されがちだが、その過ちを犯す船長には災いが待っている。ピケットがプログラムに従って標的に積極的に接近することを許せば、驚異的な密度の小口径砲火を解き放ち、装甲のない船体をズタズタに引き裂くことだろう。",
  "Sindria": "シンドリア",
  "Briefly overloads a nearby enemy ship.": "近くの敵艦を一時的にオーバーロードさせる。",
  "The value of Achaman Station is as a relatively safe port of call for the various inhabitants of Guayota's Disk to interact with traders from the Sector at-large, who otherwise rarely risk the pirates and difficult navigation of the Disk. The Tri-Tachyon Corporation, as 'caretaker' of the station, is well-situated to exploit its value handily - and do. It is often said that everything is for sale at Achaman Station.": "アチャマン・ステーションの価値は、グアヨタ・ディスクの様々な住人たちにとって、通常なら海賊の危険や困難な航海を冒してまでディスクを訪れることのないセクター全体の交易商たちと交流するための、比較的安全な寄港地であることにある。ステーションの「管理人」であるトライ・タキオン社は、その価値を手軽に搾取するのに適した立場にあり——実際にそうしている。アチャマン・ステーションではあらゆるものが売り物になる、とよく言われている。",
  "- K. Astraia, recovered from Kallichore Archive": "——K・アストライア、カリコレ・アーカイブより回収",
  "Includes ores of both ferrous and common non-ferrous metals. Must be refined to be of use to industry.   ": "鉄および一般的な非鉄金属の両方の鉱石が含まれる。工業用途に使うには精製しなければならない。   ",
  "A projecting advanced weapons platform of AI design. No internal life-support volumes; open-vacuum access tubes for maintenance drones are too small for human technicians. Features seamless integration of peculiarly aesthetic macro-to-nanoscale fractal quasicrystal morphology.": "AIの設計による、突出した先進的な兵器プラットフォーム。内部に生命維持空間はなく、メンテナンス・ドローン用の真空アクセスチューブは人間の技術者が入るには小さすぎる。特異な美しさを持つ、マクロからナノスケールに至るフラクタル準結晶形態のシームレスな統合を特徴としている。",
  "The Manticore is loved by frontier officers for its ability to rapidly bring firepower to bear in small engagements and loathed by Domain strategic planners for interfering with the orderly schema of official fleet doctrine. The Manticore's oversized primary weapon mount and built-in rangefinder are a gunner's dream but allow this destroyer to easily overextend itself in battle. That, operators argue, is what the canister flak system is for - and stripping the paint off your allied ships, as the old joke goes. \n\nA healthy respect for intimidating firepower in a small package see this design continue in the service of fleets of the Persean Sector. When the opportunity presents itself, pirates are particularly keen to recover a Manticore hull and apply blood-red livery to their overgunned prize.": "マンティコアは、小規模な交戦で迅速に火力を集中できることから辺境の士官たちに愛され、公式の艦隊ドクトリンの秩序ある図式を乱すとして人類領域(ドメイン)の戦略立案者たちからは嫌悪されている。マンティコアの巨大な主砲マウントと内蔵の測距儀は砲手にとって夢のような代物だが、そのせいでこの駆逐艦は戦闘において容易に突出してしまう。運用者たちに言わせれば、キャニスター高射砲システムはそのためにあるのだ——古い冗談で言うように、味方の船体の塗装を剥がすためにも。\n\n小型ながら威圧的な火力に対する健全な敬意から、この設計はペルセアン・セクターの艦隊で引き続き運用されている。機会があれば、海賊たちは特にマンティコアの船体を回収し、過剰武装の戦利品に血のように赤い塗装を施したがる。",
  "Abandoned Station 1": "遺棄されたステーション1",
  "A flux-efficient infrared pulse laser which fires bolts of energy at medium range. An excellent weapon for prolonged bursts of fire.\n\nThis weapon is identical to most combat lasers with a carbon dioxide gain medium fired at eleven microns. A q-switched power supply permits ablation of the target which makes the weapon much more effective than a conventional beam, at the cost of much higher power consumption. Most often used on fighters or frigates, where the low range of the weapon can be offset by the maneuverability of the fitted craft.": "フラックス効率に優れた赤外線パルスレーザーで、中距離にエネルギー弾を発射する。長時間のバースト射撃に優れた兵器。\n\nこの兵器は、波長11ミクロンで発射される二酸化炭素を媒質とする一般的な戦闘用レーザーと同一である。Qスイッチ電源が標的のアブレーションを可能にし、従来のビーム兵器よりもはるかに高い効果を発揮するが、引き換えに消費電力は非常に大きくなる。兵器の射程の短さを搭載機の機動力で補えるため、戦闘機やフリゲートで最もよく使用される。",
  "Hesperus": "ヘスペルス",
  "Among towering columns were affixed recovered landing pods of the early Luddic refugee ships, now integrated into the vaults, painted with gilt and green, bedecked with candles and hanging glass ornaments which broke the beams of the sun - filtered through ranks of high windows - into thousands of rainbow shards endlessly refracting.\n\nIt was an ecstasy of light, a galaxy unto itself.": "そびえ立つ円柱の間に、初期のルッダイト難民船から回収された着陸ポッドが据え付けられており、今や大聖堂の一部として金と緑に塗られていた。それらはキャンドルと吊り下げられたガラスの装飾品で飾られ、高い窓の列を通して差し込む太陽の光を砕き、無限に屈折する何千もの虹色の欠片に変えていた。\n\nそれは光の恍惚であり、それ自体が一つの銀河であった。",
  "Makeshift sensor arrays built using post-Collapse technology passively monitored entire star systems. An on-board transmitter was capable of encrypted real-time, FTL data transmission to friendly fleets. This telemetry would supplement fleet-based sensors, effectively increasing their power and range.": "「崩壊（コラプス）」後の技術を使って作られた急造のセンサーアレイは、星系全体をパッシブに監視していた。搭載された送信機は、友軍の艦隊に暗号化されたリアルタイムの超光速(FTL)データ送信を行うことができた。この遠隔データは艦隊ベースのセンサーを補完し、事実上その出力と探知距離を増大させていた。",
  "The Luddic Path is a loosely associated category of radical, decentralized, apocalyptic sects of Luddism that claim a truer interpretation of Ludd's Message. They view the Church as compromised and corrupt, putting worldly ego and comforts before the True Luddic Path in these, the end-times. The war of Armageddon is NOW and the lines are drawn! Only through forceful righteous action shall Good destroy Evil, and only through violence will the abomination of humanity's hubris and rebellion against God be swept aside in a final act of redemption. Or so they claim. The Luddic Path necessarily finds itself at odds with nearly all other groups in the Sector.": "ルッダイト・パスは、ルッドのメッセージのより真なる解釈を主張する、急進的で分散型の終末論的ルッダイト宗派の緩やかな連帯である。彼らは、この終末の時代において教会が堕落し腐敗しており、真なるルッダイト・パスよりも世俗的なエゴと快適さを優先していると見なしている。ハルマゲドンの戦争は今まさに起きており、戦線は引かれたのだ！ 力強い正義の行動によってのみ善は悪を滅ぼし、暴力によってのみ人類の傲慢と神への反逆という忌まわしきものは、最後の救済の行動において一掃されるだろう。——少なくとも彼らはそう主張している。ルッダイト・パスは必然的に、セクター内のほぼすべての他の派閥と対立している。",
  "The Scarab is a rare, experimental hull developed by the Tri-Tachyon corporation. Only a limited run of prototypes has been produced.\n\nGross causality violating technology was banned by the Domain, and this ban is now upheld by Hegemony doctrine - with Luddic support. Nonetheless, it is the handful of fringe-examples of this technology which form the foundation for interstellar human civilization from the old Gate system (depending on one's theory of its operation) to common FTL hyperspace travel and communication. Tri-Tachyon has always pushed the bleeding edge of these technologies - and of the law - by spearheading development of phase technology. The Scarab's uniquely hull-integrated prototype \"Temporal Shell\" system is no exception. \n\nSo it is not so much that the Scarab manipulates time as it avoids the normal rate of consequence of the local frame of reference. The effect, as upsetting to Luddic theologians as it is to laymen, is to seemingly slow time for the outside world. Of course one must avoid stating it thus in earshot of the applied temporal physicists who deal in such miracles to avoid a tedious correction of terminology. ": "スカラベは、トライ・タキオン社によって開発された希少で実験的な船体である。ごく限られた数のプロトタイプしか生産されていない。\n\n著しい因果律違反をもたらす技術は人類領域(ドメイン)によって禁じられており、現在この禁止令はヘゲモニーの教義によって——ルッダイトの支持を得て——支持されている。それにもかかわらず、古いゲートシステム（その動作に関する理論にもよるが）から一般的な超光速の超空間(ハイパースペース)の航行や通信に至るまで、星間人類文明の基盤を形成しているのは、この技術の数少ない周辺的実例なのだ。トライ・タキオンは位相（フェイズ）技術の開発を主導することで、常にこれらの技術——そして法律——の最先端を押し広げてきた。スカラベ特有の、船体に組み込まれたプロトタイプ「テンポラル・シェル」システムも例外ではない。\n\nしたがって、スカラベは時間を操作するというよりも、局所的な基準系における通常の結果の発生率を回避しているという方が正しい。その効果は、素人だけでなくルッダイトの神学者たちにとっても不穏なものであり、外の世界の時間を遅らせているように見えることだ。もちろん、そのような奇跡を扱う応用時間物理学者の耳に入る場所でこのように述べるのは避けるべきである。さもなくば、退屈な用語の訂正を受けることになるからだ。",
  "A ruling class of Tri-Tachyon executives and managers oversee a tiny polity, more a company town, built from a cut-throat web of shell corporations. The desperate and greedy in equal measure are attracted from nearby systems by the high pay. The costs, however, often prove higher.": "トライ・タキオンの役員と管理者からなる支配階級が、ダミー会社の冷酷な網の目から構築された、企業城下町とも呼べる小さな政治体を監督している。絶望した者や強欲な者が、高い報酬に等しく魅力を感じて近隣の星系から集まってくる。しかし、その代償はしばしば報酬よりも高くつくことが証明される。",
  "\"This is the largest of the anomalous vessel class thus far encountered. Not even a partial specimen has been recovered, much to the consternation of the VP of Research. Some members of the board - unofficially of course - are asking about sabotage or mutiny. I don't think you're quite getting the reality of the situation through to them.\"": "「これはこれまで遭遇した異常な艦級の中で最大のものだ。部分的な標本すら回収されておらず、研究担当副社長を大いに狼狽させている。役員会の数名は——もちろん非公式にだが——サボタージュや反乱の可能性について尋ねてきている。彼らに状況の現実が十分に伝わっているとは思えない」",
  "\"The only mercy is that it is short-lived.\"\n\n- intercepted audio log, speaker unknown": "「唯一の慈悲は、それが短命であることだ」\n\n——傍受された音声ログ、話者不明",
  "Order some available light craft to guard the area.": "利用可能な軽航空機にこのエリアの護衛を命じる。",
  "A clutch of cargo pods drifting through space. These may contain valuable goods that can be recovered, or even cryo-frozen crew that can be rescued.": "宇宙空間を漂流する一団の貨物ポッド。回収可能な貴重な物資や、あるいは救出可能な冷凍睡眠中の乗組員が含まれているかもしれない。",
  "Ultra-light orbital mirror arrays which reflect and concentrate stellar energy were a common terraforming tool. The art of their use was brought to apogee by the Eridani-Utopia Terraforming Corporation during the height of the Domain's expansion.": "星のエネルギーを反射して集光する超軽量の軌道ミラーアレイは、一般的なテラフォーミングの道具だった。その使用技術は、人類領域(ドメイン)の拡張の絶頂期にエリダニ・ユートピア・テラフォーミング社によって頂点に達した。",
  "Increases the ship's top speed and forces it to back off while firing all available weapons. The ship will vent at the end of the maneuver, and all of its ammo and charge using weapons, including missiles, will be reloaded. The system is only activated when the ship is hit by an Energy Lash.": "艦の最高速度を上昇させ、利用可能な全兵器を射撃しながら強制的に後退させる。機動の終了時に艦は排熱（ベント）を行い、ミサイルを含む弾薬やチャージを消費するすべての兵器がリロードされる。このシステムは、艦がエナジー・ラッシュの攻撃を受けた場合にのみ起動する。",
  "The ceramoid plating slowly peeled away in an aeon-long cascading fail state. Metallic ribs exposed, bleached by stellar winds, charged and released the pulsing dance of magnetic fields, the thrumming of orbits and the gnawing sirocco of micrometeorites.": "セラモイド装甲は、永遠にも似たカスケード障害の連鎖の中でゆっくりと剥がれ落ちていった。星風に漂白されて露出した金属の肋骨は、磁場の脈打つダンス、軌道の唸り、そして微小隕石の貪るような熱風を蓄え、そして解放した。",
  "Skilled personnel experienced in the maintenance and day-to-day operation of spaceships and smaller ground-based installations.": "宇宙船や小規模な地上施設のメンテナンスや日常的な運用に習熟した熟練の人員。",
  "A halo of high temperature plasma which surrounds a star; most ships are not built to withstand prolonged exposure to the extreme radiation bombardment from the corona and will take damage if they remain within it.": "恒星を囲む高温プラズマのハロー（光背）。ほとんどの船はコロナからの極端な放射線爆撃の長時間の被曝に耐えるようには造られておらず、その中に留まるとダメージを受ける。",
  "The Hydra weapon system launches a clutch of semi-independently maneuverable DEM platforms from a single device. The submunitions maneuver to flank the primary shield of the target - assumed to be directed toward the threat of the attacker - and only then unleash beamfire.\n\nThe downsides of smaller payload and increased travel time - inviting point defense interception - are generally considered to be outweighed when the Hydra is combined with a suite of complementary weapon systems to overwhelm both the tactical flexibility and physical defenses of the targeted vessel.": "ヒドラ兵器システムは、単一のデバイスから半独立して機動可能なDEMプラットフォームの群れを発射する。子弾は標的の主シールド（攻撃者の脅威に向けられていると想定される）の側面を突くように機動し、そこで初めてビーム射撃を解放する。\n\n搭載量の少なさと到達時間の増加——これがPD(近接防衛)の迎撃を招く——という欠点は、ヒドラを他の補完的な兵器システムと組み合わせて、標的艦の戦術的柔軟性と物理的防御の両方を圧倒する場合には、概して相殺されると考えられている。",
  "Although automated machines of war were forbidden in core Domain space, war drones were quietly employed outside of the officially incorporated volume. Frontier garrisons were often bolstered by drone ships, and they were deployed liberally against rebellious worlds to tip the terrible balance of attrition, setting the industrial might of the Domain versus the lives of 'freedom fighters'.\n  \nThe Bastillon was a hopeful project of Mbaye-Gogol to up-size its popular \"Defender\"-class specialized point-defense war drone. It is bigger, tougher, more heavily armed - and rather more lucrative per-unit to the MGA bottom-line.": "人類領域(ドメイン)のコア宙域では自律型戦争機械は禁じられていたが、公式に編入された宙域の外では密かに無人戦闘機（ウォードローン）が使用されていた。辺境の駐屯地はしばしばドローン艦によって補強され、反抗的な世界に対しては、ドメインの工業力と「自由の戦士」たちの命とを天秤にかけるという、恐るべき消耗戦のバランスを傾けるために惜しみなく投入された。\n  \nバスティロンは、人気の「ディフェンダー」級特化型PD(近接防衛)ウォードローンを大型化するという、ンバイェ・ゴーゴリ社の期待のプロジェクトであった。より大きく、より頑丈で、より重武装であり——そしてMGA社の利益にとって、ユニットあたりの儲けがかなり大きいものであった。",
  "A Domain-era technology, a nav buoy monitors the in-system hyperfield and is capable of transmitting its findings to friendly fleets in-system. The data readings are pristine and of great use in configuring drive fields.": "人類領域(ドメイン)時代の技術である航法ブイは、星系内のハイパーフィールドを監視し、その結果を星系内の友軍艦隊に送信することができる。そのデータ読み取り値は不純物がなく、ドライブフィールドの設定に非常に役立つ。",
  "A vice squad brute stared down all who entered. They could shut the place down at any time, but the teahouse-speakeasy provided a conduit with the commerce required for holy war. Inside was dim and crowded; the stench of drug fumes and cheap liquor competed with a disdain for pluginern enzyme soap.": "風紀取締班の無骨な男が、入ってくる者すべてを睨みつけていた。彼らはいつでもこの場所を閉鎖できたが、茶屋を装ったこの潜り酒場は聖戦に必要な商業へのパイプを提供していた。中は薄暗く混雑しており、麻薬の煙と安酒の悪臭が、現代的な酵素石鹸への軽蔑の念とせめぎ合っていた。",
  "A very high temperature and luminosity O-type star. Although extraordinarily massive this star is short-lived due to the hellish rate at which it fuses its constituent elements. It will quickly, for a star, explode as a supernova which may briefly outshine entire galaxies before transforming into a black hole or neutron star. The energies unleashed from the star's raging fusion heart erupt in powerful stellar winds that will strip the atmosphere from closely orbiting planets - and the hull from any starships that linger nearby.": "非常に高温で光度の高いO型星。とてつもなく巨大だが、この星を構成する元素が地獄のような速度で核融合を起こすため、その寿命は短い。恒星としてはあっという間に超新星として爆発し、ブラックホールや中性子星に変化する前に、一時的に銀河全体をも凌駕する輝きを放つだろう。この星の荒れ狂う核融合の中心から解き放たれるエネルギーは、強力な星風となって噴出し、近くを公転する惑星の大気を——そして近くをうろつく宇宙船の船体を——剥ぎ取ってしまう。",
  "Order all civilian craft such as freighters, tankers, and transports to gather at the designated location.": "貨物船、タンカー、輸送船などのすべての民間船に、指定された場所に集合するよう命じる。",
  "A long-range weapon designed to overload the target's shields. The heavy kinetic slug it fires is also effective against all but the heaviest armor.\n\nUses magnetic coils to accelerate a large ultra-dense composite slug to relativistic speeds. Usually rated at the hundreds of giga-amperes range, rarely exceeding one tera-ampere. And unlike most ballistic weapons, has a very high flux load when fired. Turrets mounted with this system have an extremely poor turn rate. \n\nVery effective weapon whose usefulness is limited by the low reactor power of ships that typically feature large ballistic weapon mounts. ": "標的のシールドをオーバーロードさせるために設計された長距離兵器。発射される重い実体弾（キネティック・スラッグ）は、最も厚い装甲を除くあらゆるものに対しても有効である。\n\n磁気コイルを使用して、巨大な超高密度複合弾を相対論的な速度まで加速する。通常は数百ギガアンペアの範囲で定格されており、1テラアンペアを超えることはまれである。また、ほとんどの弾道兵器とは異なり、発射時のフラックス負荷が非常に高い。このシステムを搭載したタレットは、旋回速度が極めて遅い。\n\n非常に効果的な兵器であるが、大型の弾道兵器マウントを搭載している一般的な艦船の低いリアクター出力によって、その有用性は制限されている。",
  "Ad-holos sprout around the landing bays proclaiming joyful, tasteless wickedness available for travelers who wish to decompress, for even here the moral framework of the Church rules, albeit profitably inverted. Even the Faithful benefit, for those who do visit here on business or proselytization can make a great demonstration of denying the fleshpots of Baetis.": "着陸ベイの周りには、息抜きをしたい旅行者に向けて、楽しげで低俗な悪徳行為を宣伝するホログラム広告が林立している。というのも、ここでも教会の道徳的枠組みが支配しているからだ——ただし、利益のために反転させられてはいるが。教えに忠実な者たちでさえ恩恵を受けている。ビジネスや布教活動でここを訪れる者は、ベティスの歓楽街（肉鍋）を拒絶するという偉大なデモンストレーションを行うことができるのだ。",
  "Ruins of Mairaath": "マイラースの廃墟",
  "\"There's ghosties in the old orbitals- don't you laugh, dirt-boot. It's true. I've seen 'em... or less seen 'em than felt 'em. They got signs. Static on the comms when you're in deep. Valves that come loose when you're not a-lookin'. Tools that hain't where you secured 'em. Great tombs they are, and properly ought be left sleepin' cold.\"": "「古い軌道施設には幽霊（ゴースティ）がいるんだ——笑うんじゃない、泥靴野郎。本当さ。俺は見たことがある……いや、見たというより感じたんだ。前兆がある。深部に入ると通信にノイズが走る。見てない隙にバルブが緩む。ちゃんとしまったはずの工具がそこにない。あそこは巨大な墓場なんだ。冷たい眠りにつかせたままにしておくべきなんだよ」"
}

with open("./chunk_3.json", "r", encoding="utf-8") as f:
    data = json.load(f)

output = {}
for item in data:
    if item in translations:
        output[item] = translations[item]
    else:
        # Fallback to English if not found
        print("Missing translation for:", repr(item[:50]))
        output[item] = item

with open("./chunk_3_ja.json", "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"Translation completed successfully. {len(output)} keys written.")
