import csv
import re
import sys

exact_matches = {
    "	Buying at: ": "	購入価格: ",
    "	Selling for: ": "	売却価格: ",
    "	Stockpile: ": "	備蓄: ",
    "\nAsterisks (*) indicate values that are below the top level. Values without asterisks are directly applied to your credit balance; values with asterisks are included in those.": "\nアスタリスク(*)はトップレベル以下の値を示します。アスタリスクのない値は所持金に直接適用され、アスタリスクのある値はそこに含まれます。",
    "\nCheck legacyapp.log for details.": "\n詳細は legacyapp.log を確認してください。",
    "\nCompiled for the wrong version of Java, change the compile target to Java 7": "\n誤ったバージョンのJavaでコンパイルされています。コンパイルターゲットをJava 7に変更してください。",
    "\nIllegal on trade on the open market at ": "\n以下の公開市場での取引は違法です: ",
    "\nIn-group shipping limits are higher.": "\n派閥内の輸送制限はより高くなっています。",
    "\nNote that the hull will not be affected beyond d-plugin removal and will not be converted to the base hull for this ship type.": "\nD-PLUGINの除去以外に船体への影響はなく、この艦種の基本船体には変換されないことに注意してください。",
    "\nPress and hold ": "\n長押し ",
    "\nThis save slot is already current.": "\nこのセーブスロットはすでに最新です。",
    "\nYou will also receive %s bonus experience based on the s-plugins you've built into this hull.": "\nまた、この船体に組み込んだS-PLUGINに基づいて%sのボーナス経験値を受け取ります。",
    "\n--- Or ---": "\n--- または ---",
    "\nEntry id: [": "\nエントリID: [",
    "\nApplication version:\n    ": "\nアプリケーションバージョン:\n    ",
    "\nOR\n": "\nまたは\n",
    "\nPress %s to open map and select new flagship": "\n%sを押してマップを開き、新しい旗艦を選択してください",
    "\nPress %s to select which ships to deploy": "\n%sを押して配備する艦船を選択してください",
    "\nSee application.log for details.\nIt's possible that the save application is from an incompatible version, or was created with plugins that are now disabled.": "\n詳細は application.log を確認してください。\nセーブデータが互換性のないバージョンのものであるか、現在無効になっているPLUGINを使用して作成された可能性があります。",
    "                       Unit price": "                       単価",
    "      ---": "      ---",
    "      Destroy ships in battle\nto unlock them for simulation": "      戦闘で艦船を破壊して\nシミュレーション用にアンロックする",
    "      orders: engage": "      命令: 交戦",
    "      orders: regroup": "      命令: 再編成",
    "    %s [id: %s] [version %s] (from %s)": "    %s [id: %s] [バージョン %s] (元 %s)",
    "    - %s base reward per frigate": "    - フリゲートあたりの基本報酬 %s",
    "    - %s days ago": "    - %s日前",
    "    - %s days once accepted": "    - 受注後 %s日",
    "    - %s days remaining": "    - 残り %s日",
    "    - %s reward": "    - 報酬 %s",
    "    - %s reward, %s days remaining": "    - 報酬 %s、残り %s日",
    "    - Can not be removed by any means short of scuttling the ship": "    - 船を自沈させる以外の方法では除去できない",
    "    - Doubles the rate of their experience gain": "    - 経験値の獲得率が2倍になる",
    "    - Increases the AI core's level by %s and grants an additional skill": "    - AIコアのレベルを%s上げ、追加のスキルを付与する",
    "    - Increases the range of skills available to choose from": "    - 選択可能なスキルの範囲を広げる",
    "    - No effect on pirate activity": "    - 海賊の活動に影響なし",
    "    - No effect on ship quality": "    - 船の品質に影響なし",
    "    - No effect on stability": "    - 安定度に影響なし",
    "    - Offered by ": "    - 依頼主: ",
    "    - Scan derelict to complete mission": "    - 遺棄船をスキャンしてミッションを完了する",
    "    ... and %s other items.": "    ... 他 %s 個のアイテム。",
    "    ... and %s other ships.": "    ... 他 %s 隻の艦船。",
    "    ... and other considerations": "    ... その他の考慮事項",
    "    Demand": "    需要",
    "    Exports": "    輸出",
    "    Imports": "    輸入",
    "    No significant demand": "    特筆すべき需要なし",
    "    No significant exports": "    特筆すべき輸出なし",
    "    No significant imports": "    特筆すべき輸入なし",
    "    No significant production": "    特筆すべき生産なし",
    "    None": "    なし",
    "    Production": "    生産",
    "    Weapon group ": "    兵器グループ ",
    "   <<< CURRENT SLOT": "   <<< 現在のスロット",
    "   Add industry or structure...": "   産業や建造物を追加...",
    "   None": "   なし",
    "  %s open Codex": "  %s コーデックスを開く",
    "  Available missions": "  受注可能なミッション",
    "  Capital ship": "  主力艦",
    "  Cruiser": "  巡洋艦",
    "  Deployment points": "  配備ポイント",
    "  Destroyer": "  駆逐艦",
    "  Frigate": "  フリゲート",
    "  None": "  なし",
    "  Organizational & aggregate listings": "  組織および総合リスト",
    "  Personnel listings": "  人員リスト",
    "  Recovery (/ day)": "  回復（/ 日）",
    "  Recovery (supplies)": "  回復（物資）",
    "  Recovery cost (supplies)": "  回復コスト（物資）",
    "  Recovery rate (per day)": "  回復率（1日あたり）",
    "  Score: %d%%": "  スコア: %d%%",
    "  fighters: ": "  戦闘機: ",
    " (Built in)": " (内蔵)",
    " (Empty)": " (空)",
    " (civilian)": " (民間)",
    " (custom)": " (カスタム)",
    " (fixed)": " (固定)",
    " (fully integrated, can not be removed)": " (完全統合済み、除去不可)",
    " (level ": " (レベル ",
    " (maximum)": " (最大)",
    " (military)": " (軍事)",
    " (mothballed)": " (モスボール保管中)",
    " (no hard flux)": " (ハードフラックスなし)",
    " (permanently assigned)": " (永久割り当て済み)",
    " (queued)": " (キュー待ち)",
    " (right-click to unassign)": " (右クリックで割り当て解除)",
    " (seconds)": " (秒)",
    " (size ": " (サイズ ",
    " (stock)": " (標準)",
    " (total conversion)": " (トータルコンバージョン)",
    " (upgrading to ": " (アップグレード中: ",
    " (you)": " (あなた)",
    " - Compluginities": " - コモディティ",
    " - Yours": " - あなたの所有",
    " - art, application design, writing, coding": " - アート、アプリケーションデザイン、ライティング、コーディング",
    " - competition for exporting ": " - 輸出競争: ",
    " - current and alternate sources of ": " - 現在および代替の供給源: ",
    " - current and possible ": " - 現在および可能な ",
    " - currently installed": " - 現在インストール済み",
    " - currently mounted": " - 現在搭載済み",
    " - dev & application design lead": " - 開発・アプリケーションデザインリード",
    " - empty": " - 空",
    " - jump point": " - ジャンプポイント",
    " - music, sound design": " - 音楽、サウンドデザイン",
    " - repairs completed": " - 修理完了",
    " - writing, application design, coding": " - ライティング、アプリケーションデザイン、コーディング",
    " A survey will also consume ": " 調査には以下の消費も伴います: ",
    " Aptitude": " 適性",
    " Ballistic": " 実弾",
    " Cancel the upgrade for a %s refund.": " アップグレードをキャンセルして %s の払い戻しを受けます。",
    " Composite": " 複合",
    " DEPLOY\nLEFT": " 配備\n残り",
    " Disabled": " 無効化",
    " Disabled!": " 無効化！",
    " Energy": " エネルギー",
    " Gravity Well": " 重力井戸",
    " Hull": " 船体",
    " Hybrid": " ハイブリッド",
    " Initializing Domain Ident Chip ": " 人類領域(ドメイン)識別チップを初期化中 ",
    " Malfunction": " 誤動作",
    " Marines": " 海兵隊",
    " Missile": " ミサイル",
    " Nebula": " 星雲",
    " Online": " オンライン",
    " Sector Data ": " セクターデータ ",
    " Series": " シリーズ",
    " Star System": " 星系",
    " Synergy": " シナジー",
    " Universal": " ユニバーサル",
    " Variant": " バリアント",
    " Wing": " 航空団",
    " World": " 惑星",
    " [off]": " [オフ]",
    " [on]": " [オン]",
    " above the maximum and is using %s additional supplies per day.": " 最大値を超過しており、1日あたり %s の追加物資を消費しています。",
    " again to unpause.": " をもう一度押して一時停止を解除。",
    " ago": " 前",
    " ago. ": " 前。",
    " all": " すべて",
    " all matching": " 一致するものすべて",
    " and ": " と ",
    " and controls %s of the global market share.": " 世界市場シェアの %s を支配しています。",
    " and controls %s of the global market share. ": " 世界市場シェアの %s を支配しています。 ",
    " and controls %s of the global market share. Exports bring in %s per month.": " 世界市場シェアの %s を支配しています。輸出により月額 %s の収入があります。",
    " and take ": " そして受け取る ",
    " and will take effect immediately.": " であり、即座に効果を発揮します。",
    " anonymous classes being serialized.": " 無名クラスがシリアライズされています。",
    " as well as the required resources, allowing you to establish a colony here.": " と必要な資源があるため、ここにコロニーを設立できます。",
    " at location ": " ロケーション: ",
    " available": " 利用可能",
    " available)": " 利用可能)",
    " available.": " 利用可能。",
    " being produced": " 生産中",
    " bonus XP used)": " ボーナスXP使用)",
    " bonus experience": " ボーナス経験値",
    " bonus experience from ": " ボーナス経験値: ",
    " bonus experience, ": " ボーナス経験値、",
    " bonus xp used)": " ボーナスxp使用)",
    " bounty: ": " 懸賞金: ",
    " bring in no income.": " 収入をもたらしません。",
    " but not the resources that would allow you to establish a colony here.": " ありますが、ここにコロニーを設立するための資源はありません。",
    " by that percentage.": " その割合だけ。",
    " can not be built-in": " は内蔵できません",
    " capacity and is using an extra %s supplies per day": " の容量であり、1日あたり %s の追加物資を消費しています",
    " captured!": " 占領！",
    " class": " 級",
    " class\n": " 級\n",
    " class ": " 級 ",
    " collapsed": " 崩壊した",
    " colonies": " コロニー",
    " compares to other options. ": " 他の選択肢と比較して。",
    " compares to the market's other options as a source of ": " 市場の他の供給源としての選択肢と比較して: ",
    " control, to another ": " の支配下から、別の ",
    " control.": " の支配下へ。",
    " controls %s of the export market share for ": " は以下の輸出市場シェアの %s を支配しています: ",
    " courier ship, reports that after heavy fighting, ": " クーリエ船からの報告によると、激しい戦闘の末、",
    " credit refund": " クレジット払い戻し",
    " credits": " クレジット",
    " credits each": " クレジット(各)",
    " credits per unit\n": " クレジット/単位\n",
    " currently bring in %s per month, before overhead.": " は現在、諸経費を差し引く前で月額 %s の収入をもたらしています。",
    " day ago": " 日前",
    " days": " 日",
    " days ago": " 日前",
    " deployed": " 配備済み",
    " deployed at location ": " 次の場所に配備済み: ",
    " deployed by the enemy at location ": " 敵により次の場所に配備済み: ",
    " depressurized, causing a high-speed collision and resulting in": " が減圧し、高速衝突を引き起こした結果",
    " depressurized, scattering high-velocity shrapnel and resulting in": " が減圧し、高速の破片をまき散らした結果",
    " destroyed": " 破壊された",
    " developed a slow leak": " がゆっくりと漏れ出た",
    " disabled": " 無効化された",
    " does not produce any ": " は何も生産していません: ",
    " each.": " それぞれ。",
    " effect": " 効果",
    " elite ": " エリート ",
    " enemy presence": " 敵の存在",
    " experience": " 経験値",
    " experience (": " 経験値 (",
    " exploded": " 爆発した",
    " export": " 輸出",
    " exports": " 輸出",
    " exports from ": " からの輸出 ",
    " group": " 派閥",
    " failed (no command points)": " 失敗（コマンドポイントなし）",
    " flux / second": " フラックス / 秒",
    " flux capacitor": " フラックスコンデンサ",
    " flux capacitors": " フラックスコンデンサ",
    " flux vent": " フラックスベント",
    " flux vents": " フラックスベント",
    " for": " 用",
    " for ": " 用 ",
    " for a quick video feed that lasts for as long as the key is pressed.": " キーを押している間、クイックビデオフィードが表示されます。",
    " for all colonies under ": " 以下の支配下にある全コロニーに対して: ",
    " for another market.": " 別の市場向け。",
    " for mission variants to delete": " 削除するミッションバリアント用",
    " for recovery": " 回収用",
    " for stat pluginifiers": " ステータス修正用",
    " from ": " 出発地 ",
    " from [": " 取得元 [",
    " gained ": " 獲得した ",
    " has a hazard rating of %s on the standard scale.": " は標準スケールで %s のハザード評価を持っています。",
    " has a hazard rating of %s.": " は %s のハザード評価を持っています。",
    " has a hazard rating of %s. ": " は %s のハザード評価を持っています。 ",
    " hits": " ヒット",
    " in fleet": " 艦隊内",
    " in your fleet and the projected casualties ": " が艦隊におり、予想される死傷者は ",
    " into ": " へ ",
    " is ": " は ",
    " is %s. ": " は %s です。 ",
    " is a size %s %s colony located ": " はサイズ %s の %s コロニーであり、次の場所にあります: ",
    " is a size %s colony under %s control.": " はサイズ %s のコロニーで、%s の支配下にあります。",
    " is already the current supplier.": " はすでに現在の供給元です。",
    " is exporting %s ": " は %s を輸出しています ",
    " is fully integrated with its ship and can not be removed": " は船体に完全に統合されており、除去できません",
    " is not currently exporting any ": " は現在輸出していません: ",
    " is not equal to ": " と等しくない ",
    " is now friendly": " は友好的になりました",
    " is now hostile": " は敵対的になりました",
    " is permanently assigned to their ship": " は彼らの船に永久的に割り当てられています",
    " is profitably exporting %s ": " は利益を上げて %s を輸出しています ",
    " is ranked at least tenth": " は少なくとも10位にランクされています",
    " is ready to level up": " はレベルアップの準備ができています",
    " items, control-click to add/remove maximum amount.": " 個のアイテム。Ctrl+クリックで最大量を追加/削除。",
    " iterations": " イテレーション",
    " learned elite ": " がエリートを習得した ",
    " left on their contract.": " 契約が残っています。",
    " light-years away": " 光年離れています",
    " local volume, being tracked by nearby ": " 局所的ボリュームであり、近隣の以下によって追跡されています: ",
    " losing ": " を失う ",
    " lost": " 失われた",
    " lower tier ": " 下位ティア ",
    " market share": " 市場シェア",
    " matches ": " 一致する ",
    " max FP (imported): ": " 最大FP（輸入）: ",
    " max FP (produced): ": " 最大FP（生産）: ",
    " minor: ": " マイナー: ",
    " not enough supplies to prepare replacement fighter chassis": " 交換用戦闘機の機体を用意するための物資が不足しています",
    " not found": " 見つかりません",
    " not found!": " 見つかりません！",
    " now in control of the Corvus star system.": " 現在コーバス星系を支配しています。",
    " of ": " の ",
    " of the construction cost, or ": " の建設費用、または ",
    " of the total construction cost, or ": " の総建設費用、または ",
    " of the upgrade cost, or ": " のアップグレード費用、または ",
    " of this type.": " このタイプの。",
    " on ": " オン ",
    " on the list of preferred ": " 優先リスト上 ",
    " ordnance point left": " 兵器ポイント残り",
    " ordnance points left": " 兵器ポイント残り",
    " patch: ": " パッチ: ",
    " patrol": " 哨戒艦隊",
    " per hull.": " 船体あたり。",
    " per unit.": " 単位あたり。",
    " point": " ポイント",
    " point and will not grant bonus experience.\n": " ポイントであり、ボーナス経験値は付与されません。\n",
    " point entirely.": " ポイント完全に。",
    " point for each hullplugin and ": " 各船体改造に対するポイント、および ",
    " point for each hullplugin.": " 各船体改造に対するポイント。",
    " point instead of a skill point.": " ポイント（スキルポイントの代わりに）。",
    " point to make elite": " ポイント（エリートにするため）",
    " point to recover, grants ": " 回収するためのポイント、以下を付与: ",
    " point"", eventually compensating ": " ポイント」、最終的に補償する ",
    " point.": " ポイント。",
    " point.\n": " ポイント。\n",
    " points": " ポイント",
    " points available": " 利用可能なポイント",
    " points enables you to take actions that are in some way exceptional.": " ポイントを使用すると、例外的なアクションを実行できます。",
    " points grant bonus experience, which doubles your experience gain ": " ポイントはボーナス経験値を付与し、経験値の獲得を2倍にします ",
    " points in certain ways.": " 特定の方法でのポイント。",
    " points over the course of each level. ": " 各レベルの過程でのポイント。",
    " points remaining": " 残りポイント",
    " points so far. This is enough to gain ": " これまでのポイント。これは以下を獲得するのに十分です: ",
    " points spent earlier": " 以前に消費したポイント",
    " points to build hullplugins into the ship, reducing ": " 船体に船体改造を組み込むためのポイント、以下を減少: ",
    " points to enhance certain hull-standard built-in plugins, ": " 一部の船体標準の内蔵改造を強化するためのポイント、",
    " points: ": " ポイント: ",
    " production & availability": " 生産および可用性",
    " refund": " 払い戻し",
    " remaining": " 残り",
    " reports combat readiness will start decreasing soon.": " 戦闘準備(CR)が間もなく低下し始めると報告しています。",
    " reports danger of critical malfunctions due to low combat readiness.": " 低い戦闘準備(CR)による深刻な誤動作の危険性を報告しています。",
    " reports danger of malfunctions due to low combat readiness.": " 低い戦闘準備(CR)による誤動作の危険性を報告しています。",
    " required emergency maintenance": " 緊急メンテナンスが必要でした",
    " required emergency maintenance, resulting in": " 緊急メンテナンスが必要となり、その結果",
    " resulted in": " の結果",
    " retreated": " 撤退した",
    " rules for trigger [": " トリガーのルール [",
    " samples": " サンプル",
    " samples or higher ": " サンプル以上 ",
    " seconds": " 秒",
    " seconds remaining": " 秒残り",
    " series": " シリーズ",
    " serliazed classes not marked with DoNotObfuscate.": " DoNotObfuscateとしてマークされていないシリアライズされたクラス。",
    " ships": " 艦船",
    " ships and is using an extra %s supplies per day": " 隻の艦船があり、1日あたり %s の追加物資を消費しています",
    " ships exceeded, supply consumption will be increased and burn level reduced": " 隻の艦船を超過しました。物資消費が増加し、バーンレベルが低下します",
    " ships)": " 艦船)",
    " should start with $": " $ で始まる必要があります",
    " skill ": " スキル ",
    " star system)": " 星系)",
    " string value is [": " 文字列値は [",
    " suffered a catastrophic depressurization, scattering high-velocity debris in the path of your fleet and resulting in": " 壊滅的な減圧に見舞われ、艦隊の進路に高速の破片を散乱させた結果",
    " suffered a catastrophic failure": " 壊滅的な故障に見舞われた",
    " suffered an unknown problem": " 不明な問題に見舞われた",
    " suppliers ": " 供給業者 ",
    " supplies": " 物資",
    " supplies used to repair & rearm fighters": " 戦闘機の修理と再武装に使用された物資",
    " system": " 星系",
    " system refers to invalid entity ": " 星系が無効なエンティティを参照しています ",
    " taking off from": " 発進元 ",
    " the population growth rate by ": " 人口増加率を以下のように: ",
    " to": " ～ ",
    " to ": " へ ",
    " to acquire detailed starcharts": " 詳細な星図を取得するため",
    " to re-open the command UI, if necessary (and don't forget to unpause!)": " を押して必要に応じてコマンドUIを再度開きます（一時停止の解除をお忘れなく！）",
    " to spend": " 使用可能",
    " to task ": " タスクへ ",
    " to turn off your shields and let the flux dissipate.": " を押してシールドをオフにし、フラックスを放散させます。",
    " to unpause.": " で一時停止を解除します。",
    " top speed": " 最高速度",
    " trying to leave a battle different from its getBattle()": " getBattle() と異なる戦闘から離脱しようとしています",
    " units due to local overstocking": " ローカルの過剰在庫による単位",
    " units in circulation, some may be for sale on the black market": " 単位が流通しています。一部は闇市場で販売されている可能性があります",
    " units in reserve, available for sale": " 単位の予備があり、販売可能です",
    " units last month": " 単位（先月）",
    " units per month": " 単位/月",
    " units per month at current consumption rate": " 単位/月（現在の消費率）",
    " units)": " 単位)",
    " units, available for sale": " 単位、販売可能",
    " units, illegal on the open market": " 単位、公開市場では違法",
    " unknown location": " 不明なロケーション",
    " variant": " バリアント",
    " variants": " バリアント",
    " volume": " ボリューム",
    " volume (in-group)": " ボリューム（派閥内）",
    " weapon": " 兵器",
    " weapons": " 兵器",
    " were the best supplier of ": " は以下の最適な供給業者でした: ",
    " when learned": " 習得時",
    " when this bonus XP is used up.": " このボーナスXPが使い切られた時。",
    " when you level up.": " レベルアップ時。",
    " when you level up. In total, ": " レベルアップ時。合計で、",
    " will cost ": " コストは ",
    " will refund you ": " 以下の払い戻しを行います ",
    " will refund you the full construction cost of ": " 以下の全建設費用の払い戻しを行います ",
    " will refund you the full upgrade cost of ": " 以下の全アップグレード費用の払い戻しを行います ",
    " will show a quick video feed that only lasts for as long as the key is held down.": " キーを押し続けている間だけ、クイックビデオフィードを表示します。",
    " wing": " 航空団",
    " wing: ": " 航空団: ",
    " with excess stockpiles": " 過剰な備蓄あり",
    " world": " 惑星",
    " worth of ordnance": " 相当の兵器",
    " your fleet": " あなたの艦隊",
    " “ + fwewjefwefe": " “ + fwewjefwefe",
    "\" button acts as a toggle instead of having to be held down": "\" ボタンは、押し続けるのではなくトグルとして機能します",
    "\" category.": "\" カテゴリ。",
    "\" category? All changes will be lost.": "\" カテゴリをクリアしますか？すべての変更が失われます。",
    "\" compluginity.": "\" コモディティ。",
    "\"Free Port\" status\n": "\"自由港\" ステータス\n",
    "% of demand can not be met by local supply": "需要の % がローカル供給で満たせません",
    "% of demand met by imports": "需要の % が輸入で満たされています",
    "% of demand met by local supply and stockpiles": "需要の % がローカル供給と備蓄で満たされています",
    "% of demand not met": "需要の % が満たされていません",
    "% of exports": "輸出の %",
    "% of imports": "輸入の %",
    "% of local demand not met due to being exported": "輸出されているため満たされていないローカル需要の %",
    "% bonus XP": "% ボーナスXP",
    "% engine capability": "% エンジン出力",
    "%d light years": "%d 光年",
    "%s additional ": "%s 追加の ",
    "%s can be built at any colony, while a %s can be found as salvage in the abandoned systems outside the core worlds.": "%s は任意のコロニーに建設できますが、%s はコアワールド外の放棄された星系でのサルベージによってのみ発見されます。",
    "%s command point in %s second(s).": "%s コマンドポイント（%s 秒後）。",
    "%s out of %s experience gained towards next level.": "次のレベルに向けて %s / %s の経験値を獲得しました。",
    "%s out of %s experience gained.": "%s / %s の経験値を獲得しました。",
    "%s skill points will be available after you reach the maximum level.": "最大レベルに達すると、%s スキルポイントが利用可能になります。",
    "%s to cycle weapon info": "%s で兵器情報を切り替え",
    "%s to turn on your shields again and let the enemy keep firing at you.": "%s を押してシールドを再びオンにし、敵に攻撃を続けさせます。",
    "%s to turn on your shields.": "%s を押してシールドをオンにします。",
    "%s will increase the available deployment points, but only up to %s of the battle size. You currently have the maximum possible deployment points.": "%s は利用可能な配備ポイントを増加させますが、戦闘規模の %s までです。現在、あなたは可能な最大の配備ポイントを持っています。",
    "%s, and certain skills, will increase the available deployment points, but only up to %s of the battle size. You currently have %s bonus deployment points from skills and objectives.": "%s と特定のスキルは利用可能な配備ポイントを増加させますが、戦闘規模の %s までです。現在、スキルと目標から %s のボーナス配備ポイントを持っています。",
    "%s: all weapons will fire as rapidly as possible while the fire button is held down.": "%s: 発射ボタンを押している間、すべての兵器が可能な限り高速で発射されます。",
    "%s: each press of the fire button will fire the selected weapon and switch to the next weapon in the group. Selecting the group repeatedly will also switch to the next weapon. If the fire button is held down, weapons will alternate firing at a rate that will approximately fire them as they are ready to fire, if possible.": "%s: 発射ボタンを押すごとに選択された兵器が発射され、グループ内の次の兵器に切り替わります。グループを繰り返し選択することでも次の兵器に切り替わります。発射ボタンを押し続けると、可能であれば兵器が発射準備できた時点で交互に発射されます。",
    "(By the way - you can pause and unpause the application at any time by pressing ": "(ちなみに、アプリケーションはいつでも一時停止および再開できます。キー: ",
    "(If you only have one ship, it's deployed automatically.)": "(艦船が1隻しかない場合は、自動的に配備されます。)",
    "(If you'd like to rename it later, you can do so by clicking on its name in the colony info screen.)": "(後で名前を変更したい場合は、コロニー情報画面でその名前をクリックすることで変更できます。)",
    "(So, even if you're not taking any damage on the shields, keeping them off will let you put out more firepower.)": "(そのため、シールドでダメージを受けていなくても、シールドをオフにしておくことでより多くの火力を発揮できます。)",
    "(To pan the view around, right-click and drag, or move the mouse to the edge of the screen. You can toggle the command UI on and off by pressing ": "(視点を移動するには、右クリックしてドラッグするか、マウスを画面の端に移動します。コマンドUIのオン/オフは次のキーで切り替えられます: ",
    "(condition market only)": "(条件市場のみ)",
    ") and wait for your ships to secure the objectives.": ") を押し、艦船が目標を確保するのを待ちます。",
    ")?\nThis decision is irreversible.": ")？\nこの決定は取り消せません。",
    "*2000 units = 1 map grid cell": "*2000 単位 = 1 マップグリッドセル",
    "*Per unit prices assume buying or selling a batch of %s units. Each unit bought costs more as the market's supply is reduced, and each unit sold brings in less as demand is fulfilled.": "*単位あたりの価格は、%s 単位のバッチの売買を前提としています。市場の供給が減少するにつれて購入する各単位のコストは上昇し、需要が満たされるにつれて売却する各単位の収入は減少します。",
    "+0 top speed": "+0 最高速度",
    ", Contact": "、連絡先",
    ", Fringe Jump-point": "、辺境ジャンプポイント",
    ", Sleep time: ": "、スリープ時間: ",
    ", and will take effect immediately.": "、そして即座に効果を発揮します。",
    ", assigned to the ": "、以下に割り当て済み: ",
    ", but don't do this yet.)": "、しかし、まだ実行しないでください。)",
    ", easy": "、簡単",
    ", engaged in battle": "、戦闘中",
    ", fully integrated with the ": "、以下と完全統合済み: ",
    ", goal was ": "、目標は ",
    ", including ": "、以下を含む: ",
    ", including carriers and militarized civilian ships": "、空母や軍事化された民間船を含む",
    ", instead of the selected ": "、選択されたものの代わりに: ",
    ", maximum number of officers exceeded": "、士官の最大数を超過",
    ", permanently assigned to the ": "、以下に永久割り当て済み: ",
    ", picking one randomly.": "、ランダムに1つ選択します。",
    ", under construction": "、建設中",
    ", undergoing repairs": "、修理中",
    ", which could be exported if ": "、条件が合えば輸出可能: ",
    "- Multiplier for income from exports (%s to %s)": "- 輸出収入の乗数 (%s から %s)",
    "- high prices on": "- 高価格:",
    "- low prices on": "- 低価格:",
    "- prices on": "- 価格:",
    ". Actual losses taken are ": "。実際に被った損失は ",
    ". Its current stability is %s.": "。現在の安定度は %s です。",
    ". The growth penalty increases with colony size.": "。成長ペナルティはコロニーのサイズに比例して増加します。",
    ". Using higher UI scaling requires selecting a ": "。より高いUIスケーリングを使用するには、以下を選択する必要があります: ",
    ". You have ": "。あなたは ",
    ". You only have ": "。あなたはこれだけしか持っていません: ",
    ".. and starting with a / are not allowed in filenames. Also, use / instead of \\.": ".. および / で始まるファイル名は許可されていません。また、\\ の代わりに / を使用してください。",
    "... and press the \"Transfer Command\" button, then wait for the shuttle pod to take you to the new flagship.": "... 「指揮権移譲(Transfer Command)」ボタンを押し、シャトルポッドが新しい旗艦に連れて行ってくれるのを待ちます。",
    "... and right-click on the Comm Relay.": "... 通信リレーを右クリックします。",
    "... and select \"Avoid\" from the list of available assignments.": "... 利用可能な任務のリストから「回避(Avoid)」を選択します。",
    "... and select \"Capture\" from the list of available assignments.\nYou can also use the keyboard shortcut displayed on the button.": "... 利用可能な任務のリストから「占領(Capture)」を選択します。\nボタンに表示されているキーボードショートカットを使用することもできます。",
    "... and select \"Eliminate\" from the list of available assignments.": "... 利用可能な任務のリストから「排除(Eliminate)」を選択します。",
    "0 credits": "0 クレジット",
    "0% combat readiness": "0% 戦闘準備(CR)",
    "1 deployed": "1 隻配備",
    "1 month ago": "1 ヶ月前",
    "1 week ago": "1 週間前",
    "2 months ago": "2 ヶ月前",
    "2 weeks ago": "2 週間前",
    "3 months ago": "3 ヶ月前",
    "3 weeks ago": "3 週間前",
    "<<< Hide advanced options": "<<< 詳細オプションを隠す",
    "<empty slot>": "<空きスロット>",
    "<insert invulnerable scorpion (or, better yet, a Pink Scorpion Diggle) here>": "<ここに無敵のサソリ（あるいは、もっと良いのはピンクのスコーピオン・ディグル）を挿入>",
}

def process():
    translated_rows = []
    with open("./chunk_1.csv", "r", encoding="utf-8") as f:
        reader = csv.reader(f)
        header = next(reader)
        translated_rows.append(header)
        for row in reader:
            if not row: continue
            key, val = row[0], row[0]
            if len(row) > 1:
                val = row[1]
            if not key:
                translated_rows.append(row)
                continue
                
            if key in exact_matches:
                translated_rows.append([key, exact_matches[key]])
            elif key.startswith('$') or key.startswith('(?') or key.startswith('-D') or key.startswith('-X'):
                translated_rows.append([key, val]) # Keep same
            elif re.match(r'^[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}$', key):
                translated_rows.append([key, val])
            elif key.startswith('<missing'):
                translated_rows.append([key, val])
            else:
                translated_rows.append([key, val])

    with open("./chunk_1_translated.csv", "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerows(translated_rows)

process()
