import json
import codecs

data1 = {
    "campaign\\\\market_conditions.csv|uninhabitable|name": "居住不能世界",
    "campaign\\\\market_conditions.csv|ice|desc": "$Marketの平均気温は水の氷点をはるかに下回り、地球上で一般的な大気ガスの一部は雪として降っています。軽く揮発性の高い元素の漂流物や氷河を採取することができます。",
    "campaign\\\\market_conditions.csv|ice|name": "氷雪世界",
    "campaign\\\\market_conditions.csv|desert|desc": "$Market: 砂漠の惑星。乾生植物の生物圏により、簡易マスクだけで呼吸可能な大気が維持されています。農業はほぼ不可能です。",
    "campaign\\\\market_conditions.csv|desert|name": "砂漠世界",
    "campaign\\\\market_conditions.csv|arid|desc": "$Marketは広大な乾燥した平原や荒れ地に覆われています。水は珍しく、大規模な農業は困難です。",
    "campaign\\\\market_conditions.csv|arid|name": "乾燥世界",
    "campaign\\\\market_conditions.csv|water|desc": "$marketの気候は快適ですが、農業は主に水産養殖に限られており、居住地や産業の開発には高度に専門化されたインフラが必要です。",
    "campaign\\\\market_conditions.csv|water|name": "水界世界",
    "campaign\\\\market_conditions.csv|jungle|desc": "$Marketは、鬱蒼とした植生とエキゾチックな生命体に覆われた、湿潤で温暖なジャングル世界であり、農業や恒久的なインフラの維持は困難です。",
    "campaign\\\\market_conditions.csv|jungle|name": "ジャングル世界",
    "campaign\\\\market_conditions.csv|terran|desc": "$Marketは、セクター内で見つけられる限り古き地球の環境に最も近く、農業や定住に理想的な条件を提供しています。",
    "campaign\\\\market_conditions.csv|terran|name": "テラン世界",
    "campaign\\\\market_conditions.csv|barren_marginal|desc": "$marketの過酷で容赦のない外部環境は、呼吸用マスクや防護装備がなければ人間が生存することは困難ですが、一部の遺伝子組み換えされたテラフォーミング用地衣類にとっては許容できる環境です。",
    "campaign\\\\market_conditions.csv|barren_marginal|name": "不毛の辺境世界",
    "campaign\\\\market_conditions.csv|twilight|desc": "主星に自転と公転が同期(潮汐ロック)している、またはそれに近い$marketは、四季と同じ長さの昼夜を持つテラフォーミングされた世界です。そのため、遺伝子組み換えされた地球の生命体にとってさえ、昼夜の寒暖差は過酷です。「文明化」された穏やかなバイオームの島々は、日よけと鏡の慎重な使用によって維持されています。",
    "campaign\\\\market_conditions.csv|twilight|name": "薄明世界",
    "campaign\\\\market_conditions.csv|tundra|desc": "テラフォーミングによって地球の生命体が$marketにもたらされましたが、この世界は地球の最も深い氷河期と同じくらい寒冷なままです。数百万平方キロメートルが氷河に覆われていますが、より温暖なタイガ地帯やなだらかなステップ地帯も存在します。",
    "campaign\\\\market_conditions.csv|tundra|name": "ツンドラ世界",
    "campaign\\\\market_conditions.csv|cryovolcanic|desc": "極寒を超えて凍りついた世界。水の氷の山々にメタンの雪が降り、火山からはアンモニアが噴出しています。恒星からの放射線が揮発性物質を分解して窒素や酸素などの軽いガスの大気を形成し、水素は宇宙空間へと散逸していきます。",
    "campaign\\\\market_conditions.csv|cryovolcanic|name": "氷雪火山世界",
    "campaign\\\\market_conditions.csv|dissident|desc": "$Marketは、反体制派、反逆者、自由思想家、芸術家、その他のトラブルメーカーの掃き溜めとなっています。群衆を取り締まるための武器や海兵隊の需要が増加します。移住によって乗組員の供給も増加します。",
    "campaign\\\\market_conditions.csv|dissident|name": "反体制派の住民",
    "campaign\\\\market_conditions.csv|headquarters|desc": "$Marketは、支配体制の中核的な軍事司令部および物流作戦の中心地です。市場の安定性が向上します。\\n\\n$marketの艦隊における将校の質と量が増加します。",
    "campaign\\\\market_conditions.csv|headquarters|name": "司令部",
    "campaign\\\\market_conditions.csv|hydroponics_complex|desc": "軌道上や過酷な世界の地表での農業を可能にする、密閉バイオスフィア農業生産施設。運用には乗組員、有機培地、そして維持のための重機が必要です。",
    "campaign\\\\market_conditions.csv|hydroponics_complex|name": "水耕栽培施設",
    "campaign\\\\market_conditions.csv|population_1|desc": "恒久的にここに住んでいるのはわずか数十人です。",
    "campaign\\\\market_conditions.csv|population_1|name": "人口",
    "campaign\\\\market_conditions.csv|population_2|desc": "わずか数百人が$marketNameに住んでいます。",
    "campaign\\\\market_conditions.csv|population_2|name": "人口",
    "campaign\\\\market_conditions.csv|population_3|desc": "数千人が$marketNameを故郷と呼んでいます。",
    "campaign\\\\market_conditions.csv|population_3|name": "人口",
    "campaign\\\\market_conditions.csv|population_4|desc": "数万人が$marketNameに住んでいます。",
    "campaign\\\\market_conditions.csv|population_4|name": "人口",
    "campaign\\\\market_conditions.csv|population_5|desc": "$MarketNameには数十万人が住んでいます。",
    "campaign\\\\market_conditions.csv|population_5|name": "人口",
    "campaign\\\\market_conditions.csv|population_6|desc": "$marketNameの人口は数百万人に達します。",
    "campaign\\\\market_conditions.csv|population_6|name": "人口",
    "campaign\\\\market_conditions.csv|population_7|desc": "$MarketNameは数千万人の人口を抱える世界です。",
    "campaign\\\\market_conditions.csv|population_7|name": "人口",
    "campaign\\\\market_conditions.csv|population_8|desc": "$MarketNameは、セクター内で数億の人口を抱える数少ない世界のひとつです。",
    "campaign\\\\market_conditions.csv|population_8|name": "人口",
    "campaign\\\\market_conditions.csv|population_9|desc": "危険な銀河における人類の貴重な避難所である$marketNameには、数十億の魂が住んでいます。",
    "campaign\\\\market_conditions.csv|population_9|name": "人口",
    "campaign\\\\market_conditions.csv|population_10|desc": "$MarketNameはセクターにおける主要な人口集積地であり、数百億の人々が暮らす古き地球のライバルです。",
    "campaign\\\\market_conditions.csv|population_10|name": "人口",
    "campaign\\\\market_conditions.csv||name": "# procgen conditions",
    "campaign\\\\market_conditions.csv|event_food_shortage|desc": "現在、$marketでは利用可能な食料が一時的に不足しています。\\n- 安定性が $stabilityPenalty 低下\\n- 食料不足を終わらせるには約 $neededFood ユニットの食料が必要\\n- 食料供給の低下により食料価格が上昇\\n- 食料を販売することで得られる評判と経験値が増加",
    "campaign\\\\market_conditions.csv|event_food_shortage|name": "食糧不足",
    "campaign\\\\market_conditions.csv|recent_unrest|desc": "$Marketは最近、安定性に後を引く影響を与える騒々しい出来事を経験しました。",
    "campaign\\\\market_conditions.csv|recent_unrest|name": "最近の騒乱",
    "campaign\\\\market_conditions.csv|event_trade_disruption|desc": "$marketを発着する貿易艦隊が大きな損失を被っています。海賊行為か戦争が最も可能性の高い原因です。\\n\\n以下の物資が影響を受けています:\\n$compluginitySummary",
    "campaign\\\\market_conditions.csv|event_trade_disruption|name": "貿易の混乱",
    "campaign\\\\market_conditions.csv|event_smuggling|desc": "$marketでは密輸活動が多発しています。\\n\\n- 安定性が $smugglingPenalty 低下",
    "campaign\\\\market_conditions.csv|event_smuggling|name": "密輸",
    "campaign\\\\market_conditions.csv|event_bounty|name": "星系賞金",
    "campaign\\\\market_conditions.csv|rogue_ai_core|desc": "$market上、またはその近くで稼働しているローグAIコアが存在します。自身の生存を超えた、その長期的な計画や野望は不明です。\\n\\n少なくとも、その潜在的な行動に対する警戒が必要であり、日々の活動の効率を低下させ、不安を煽る噂の温床となっています。",
    "campaign\\\\market_conditions.csv|rogue_ai_core|name": "ローグAIコア"
}

with codecs.open("phase6_csv_chunk_1_ja.json", "w", encoding="utf-8") as f:
    json.dump(data1, f, ensure_ascii=False, indent=4)
